<?php //Please do NOT edit this file, use the admin page for changes.

// All this can be retrieved from Wordpress I think.
$GLOBALS['title'] = 'Wobi Wordpress Bittorrent';
$dbhost = 'localhost'; // Your database host
$dbuser = ''; // Your database user
$dbpass = ''; // Your database password
$database = ''; // Your database name

$GLOBALS['hiddentracker'] = false;
$GLOBALS['scrape'] = true;
$GLOBALS['report_interval'] = 1800;
$GLOBALS['min_interval'] = 300;
$GLOBALS['maxpeers'] = 50;
$GLOBALS['NAT'] = false;
$GLOBALS['persist'] = false;
$GLOBALS['ip_override'] = false;
$GLOBALS['countbytes'] = true;
$upload_username = 'upload';
$upload_password = '85cf60aa2f1d2941aa4cda9d56d5f6e4';
$admin_username = 'admin';
$admin_password = 'f50da7a1fb642fceef1657863e1e1858';
$enablerss = false;
$rss_title = 'Wobi Bittorrent Tracker';
$rss_link = '';
$rss_description = '';
$website_url = ''; // You website
$GLOBALS['max_upload_rate'] = 2046;
$GLOBALS['max_uploads'] = 10;
$timezone = '+0000';
$prefix = 'rt_';
?>
